# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: Python Package magic

on: [push, pull_request]

jobs:
  demo4:
    runs-on: ubuntu-latest
    container:
      image: python

    env:
      MY_KEY_DEMO4: ${{ secrets.MY_KEY_DEMO4 }}
      my_key1: ${{ secrets.MY_KEY1 }}

    
    steps:
    - uses: actions/checkout@v4
    - name: Use variables
      run: |
        echo "repository variable : '$MY_KEY_DEMO4'"
        echo "2nd var :  '$my_key1'"
    # - name: Set up Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: '3.x'

    - name: Install dependencies
      run: |
          echo "sample print statement"
        # python -m pip install --upgrade pip
        # pip install build

    - name: Run code
      run: python hello.py

    - name: Upload code output as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: code-output
        path: |
          artifacts_sample_demo4.txt
 




# name: Python Package magic

# on: [push, pull_request]


# jobs:
#   demo4:

#     runs-on: ubuntu-latest
#     container:
#       image: python

#     steps:
#     - uses: actions/checkout@v4
#     # - name: Set up Python
#     #   uses: actions/setup-python@v3
#     #   with:
#     #     python-version: '3.x'
#     - name: Install dependencies
#       run: |
#           echo "sample print statement"
#         # python -m pip install --upgrade pip
#         # pip install build
#     - name : run code
#       run: python hello.py
   
